services:

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://walkingbus:password@db:5432/walkingbus
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=${SECRET_KEY}
      - WALKING_BUSES=1:bus_name1:password1,2:bus_name2:password2
      - FLASK_ENV=production
      - HOLIDAY_COUNTRY=DE
      - HOLIDAY_SUBDIVISION=NW
      - OPENWEATHER_API_KEY={your_api_key_here}
      - WEATHER_LAT=50.6612
      - WEATHER_LON=6.7871
      - VAPID_EMAIL=your@email.com
      - SHA256_FINGERPRINT=${SHA256_FINGERPRINT}
    volumes:
      - vapid_keys:/app/data

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=walkingbus
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=walkingbus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U walkingbus"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  scheduler:
    build: 
      context: .
      dockerfile: Dockerfile.scheduler
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      web:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://walkingbus:password@db:5432/walkingbus
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_ENV=production
      - VAPID_EMAIL=your@email.com
    volumes:
      - vapid_keys:/app/data

  registration:
    build: 
      context: .
      dockerfile: Dockerfile.registration
    ports:
      - "8001:5001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://walkingbus:password@db:5432/walkingbus
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_ENV=production
      - PORT=5001
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - SCHOOL_COORDINATES=${SCHOOL_COORDINATES:-52.5200,13.4050}
      - SCHOOL_RADIUS=${SCHOOL_RADIUS:-30}
    volumes:
      - ./registration_app:/app/registration_app

volumes:
  postgres_data:
  vapid_keys:
