FROM python:3.10-slim

WORKDIR /app

# Install system dependencies needed for Python packages
RUN apt-get update --fix-missing && \
    apt-get install -y --no-install-recommends gcc libpq-dev && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "-m", "app.scheduler_worker"]