services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=walkingbus
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=walkingbus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U walkingbus"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
