"""Add attendance field to CalendarStatus

Revision ID: 1020c31b169b
Revises: 3f45c424bd68
Create Date: 2025-07-09 12:12:59.226371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1020c31b169b'
down_revision = '3f45c424bd68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_status', schema=None) as batch_op:
        batch_op.drop_column('attendance')

    # ### end Alembic commands ###
