"""Add Auth Token Database

Revision ID: 1c8955683387
Revises: 002de5366907
Create Date: 2025-01-15 12:51:57.163635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c8955683387'
down_revision = '002de5366907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tokens',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('walking_bus_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(), nullable=True),
    sa.Column('invalidation_reason', sa.String(length=100), nullable=True),
    sa.Column('token_identifier', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['walking_bus_id'], ['walking_bus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_identifier')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_tokens')
    # ### end Alembic commands ###
