"""Add push subscription table

Revision ID: 2136bf8a984f
Revises: 26f461b8eaf5
Create Date: 2025-02-09 10:37:18.062853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2136bf8a984f'
down_revision = '26f461b8eaf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_identifier', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('p256dh', sa.String(length=200), nullable=False),
    sa.Column('auth', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('walking_bus_id', sa.Integer(), nullable=False),
    sa.Column('participant_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['token_identifier'], ['auth_tokens.token_identifier'], ),
    sa.ForeignKeyConstraint(['walking_bus_id'], ['walking_bus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_identifier', 'endpoint', name='uq_subscription_token_endpoint')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('push_subscription')
    # ### end Alembic commands ###
