"""initial setup

Revision ID: 264e4966c6b7
Revises: 7f936a424b34
Create Date: 2025-01-03 21:46:32.538690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264e4966c6b7'
down_revision = '7f936a424b34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walking_bus_override', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walking_bus_override', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
