"""Add WeatherCalculation table

Revision ID: 26f461b8eaf5
Revises: 76ace0377534
Create Date: 2025-01-22 17:12:22.929713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f461b8eaf5'
down_revision = '76ace0377534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_calculation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('walking_bus_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('precipitation', sa.Float(), nullable=True),
    sa.Column('pop', sa.Float(), nullable=True),
    sa.Column('calculation_type', sa.String(length=20), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['walking_bus_id'], ['walking_bus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('walking_bus_id', 'date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_calculation')
    # ### end Alembic commands ###
