"""Add default times

Revision ID: 398d1f1b8abd
Revises: fc8d01e0048b
Create Date: 2025-01-05 21:35:20.043731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '398d1f1b8abd'
down_revision = 'fc8d01e0048b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walking_bus_schedule', schema=None) as batch_op:
        batch_op.alter_column('monday_start',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('monday_end',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('tuesday_start',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('tuesday_end',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('wednesday_start',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('wednesday_end',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('thursday_start',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('thursday_end',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('friday_start',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('friday_end',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('saturday_start',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('saturday_end',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('sunday_start',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('sunday_end',
               existing_type=postgresql.TIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walking_bus_schedule', schema=None) as batch_op:
        batch_op.alter_column('sunday_end',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('sunday_start',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('saturday_end',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('saturday_start',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('friday_end',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('friday_start',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('thursday_end',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('thursday_start',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('wednesday_end',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('wednesday_start',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('tuesday_end',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('tuesday_start',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('monday_end',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('monday_start',
               existing_type=postgresql.TIME(),
               nullable=True)

    # ### end Alembic commands ###
