"""Added second phone and accompaniment

Revision ID: 3f45c424bd68
Revises: 9448a95d3926
Create Date: 2025-07-07 14:16:50.041915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f45c424bd68'
down_revision = '9448a95d3926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prospects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_secondary', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('accompaniment_type', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prospects', schema=None) as batch_op:
        batch_op.drop_column('accompaniment_type')
        batch_op.drop_column('phone_secondary')

    # ### end Alembic commands ###
