"""Add weather table

Revision ID: 513af671a617
Revises: afa1ac9b39f9
Create Date: 2025-01-21 13:15:14.289638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '513af671a617'
down_revision = 'afa1ac9b39f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('forecast_type', sa.String(length=10), nullable=False),
    sa.Column('precipitation', sa.Float(), nullable=True),
    sa.Column('total_precipitation', sa.Float(), nullable=True),
    sa.Column('pop', sa.Float(), nullable=True),
    sa.Column('weather_icon', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp', 'forecast_type')
    )
    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    op.drop_table('weather')
    # ### end Alembic commands ###
