"""add min_companions to walking_bus

Revision ID: 543ad0849e9c
Revises: 8a9092cdcd17
Create Date: 2025-08-10 14:47:54.558959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543ad0849e9c'
down_revision = '8a9092cdcd17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walking_bus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_companions', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walking_bus', schema=None) as batch_op:
        batch_op.drop_column('min_companions')

    # ### end Alembic commands ###
