"""Make walking_bus_route_id nullable

Revision ID: 65bbb1ada158
Revises: 8d1f78f626a9
Create Date: 2025-07-05 11:12:06.030774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65bbb1ada158'
down_revision = '8d1f78f626a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prospects', schema=None) as batch_op:
        batch_op.alter_column('walking_bus_route_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prospects', schema=None) as batch_op:
        batch_op.alter_column('walking_bus_route_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
