"""Add CompanionCustomSchedule model for individual schedules

Revision ID: 67625e0a0a5e
Revises: change_min_companions_default
Create Date: 2025-08-26 08:46:08.917132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67625e0a0a5e'
down_revision = 'change_min_companions_default'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companion_custom_schedules',
    sa.Column('walking_bus_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companion_id', sa.Integer(), nullable=False),
    sa.Column('pattern_type', sa.String(length=20), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('interval_weeks', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['companion_id'], ['companions.id'], ),
    sa.ForeignKeyConstraint(['walking_bus_id'], ['walking_bus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companion_custom_schedules')
    # ### end Alembic commands ###
