"""Add Companion and CompanionSchedule models

Revision ID: 8a9092cdcd17
Revises: 1020c31b169b
Create Date: 2025-08-08 10:25:25.301711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9092cdcd17'
down_revision = '1020c31b169b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companions',
    sa.Column('walking_bus_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('monday', sa.Boolean(), nullable=True),
    sa.Column('tuesday', sa.Boolean(), nullable=True),
    sa.Column('wednesday', sa.Boolean(), nullable=True),
    sa.Column('thursday', sa.Boolean(), nullable=True),
    sa.Column('friday', sa.Boolean(), nullable=True),
    sa.Column('saturday', sa.Boolean(), nullable=True),
    sa.Column('sunday', sa.Boolean(), nullable=True),
    sa.Column('is_substitute', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['walking_bus_id'], ['walking_bus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companion_schedules',
    sa.Column('walking_bus_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companion_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_scheduled', sa.Boolean(), nullable=True),
    sa.Column('is_manual_override', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['companion_id'], ['companions.id'], ),
    sa.ForeignKeyConstraint(['walking_bus_id'], ['walking_bus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('companion_id', 'date', name='uq_companion_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companion_schedules')
    op.drop_table('companions')
    # ### end Alembic commands ###
