"""Remove foreign key and unique constraints from token_identifier

Revision ID: 8c45d646d917
Revises: 543ad0849e9c
Create Date: 2025-08-11 20:10:04.354377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c45d646d917'
down_revision = '543ad0849e9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraint first, then unique constraint
    with op.batch_alter_table('push_subscription', schema=None) as batch_op:
        batch_op.drop_constraint('push_subscription_token_identifier_fkey', type_='foreignkey')

    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.drop_constraint('auth_tokens_token_identifier_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_subscription', schema=None) as batch_op:
        batch_op.create_foreign_key('push_subscription_token_identifier_fkey', 'auth_tokens', ['token_identifier'], ['token_identifier'])

    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.create_unique_constraint('auth_tokens_token_identifier_key', ['token_identifier'])

    # ### end Alembic commands ###
