"""Registration added last name

Revision ID: 9448a95d3926
Revises: 65bbb1ada158
Create Date: 2025-07-05 11:48:13.486502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9448a95d3926'
down_revision = '65bbb1ada158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prospects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('child_first_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('child_last_name', sa.String(length=100), nullable=False))
        batch_op.drop_column('child_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prospects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('child_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('child_last_name')
        batch_op.drop_column('child_first_name')

    # ### end Alembic commands ###
