"""Add pwa status

Revision ID: a7e2878e47d5
Revises: d389bbddeef1
Create Date: 2025-02-14 19:39:26.325783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e2878e47d5'
down_revision = 'd389bbddeef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pwa_installed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pwa_status_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.drop_column('pwa_status_updated_at')
        batch_op.drop_column('is_pwa_installed')

    # ### end Alembic commands ###
