"""Add route preference

Revision ID: a9dda3838f8e
Revises: 98d149baf406
Create Date: 2025-07-04 08:29:47.856171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9dda3838f8e'
down_revision = '98d149baf406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prospects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('route_preference', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'routes', ['route_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prospects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('route_preference')
        batch_op.drop_column('route_id')

    # ### end Alembic commands ###
