"""Add pwa temp token

Revision ID: b4315f85c732
Revises: a7e2878e47d5
Create Date: 2025-02-15 11:55:57.399708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4315f85c732'
down_revision = 'a7e2878e47d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pwa_token', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('token_identifier', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp_tokens', schema=None) as batch_op:
        batch_op.drop_column('token_identifier')
        batch_op.drop_column('is_pwa_token')

    # ### end Alembic commands ###
