"""increase pause_reason length

Revision ID: d389bbddeef1
Revises: cac9734c4964
Create Date: 2025-02-12 09:49:18.894942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd389bbddeef1'
down_revision = 'cac9734c4964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_subscription', schema=None) as batch_op:
        batch_op.alter_column('pause_reason',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_subscription', schema=None) as batch_op:
        batch_op.alter_column('pause_reason',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
