"""Add SchedulerJob tables

Revision ID: d4cdeaa1542a
Revises: 2136bf8a984f
Create Date: 2025-02-11 09:12:07.852843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4cdeaa1542a'
down_revision = '2136bf8a984f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('walking_bus_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=191), nullable=False),
    sa.Column('next_run_time', sa.DateTime(), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['walking_bus_id'], ['walking_bus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('scheduler_jobs')
    # ### end Alembic commands ###
