"""initial setup

Revision ID: dbb134c39670
Revises: 264e4966c6b7
Create Date: 2025-01-03 21:51:08.889104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb134c39670'
down_revision = '264e4966c6b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('walking_bus_override', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walking_bus_override', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    op.drop_table('daily_note')
    # ### end Alembic commands ###
