"""Add schedule times

Revision ID: fc8d01e0048b
Revises: dbb134c39670
Create Date: 2025-01-05 19:53:03.637013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc8d01e0048b'
down_revision = 'dbb134c39670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walking_bus_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monday_start', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('monday_end', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('tuesday_start', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('tuesday_end', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('wednesday_start', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('wednesday_end', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('thursday_start', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('thursday_end', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('friday_start', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('friday_end', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('saturday_start', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('saturday_end', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('sunday_start', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('sunday_end', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walking_bus_schedule', schema=None) as batch_op:
        batch_op.drop_column('sunday_end')
        batch_op.drop_column('sunday_start')
        batch_op.drop_column('saturday_end')
        batch_op.drop_column('saturday_start')
        batch_op.drop_column('friday_end')
        batch_op.drop_column('friday_start')
        batch_op.drop_column('thursday_end')
        batch_op.drop_column('thursday_start')
        batch_op.drop_column('wednesday_end')
        batch_op.drop_column('wednesday_start')
        batch_op.drop_column('tuesday_end')
        batch_op.drop_column('tuesday_start')
        batch_op.drop_column('monday_end')
        batch_op.drop_column('monday_start')

    # ### end Alembic commands ###
